on:
  push:
    branches: 
      - master
      - main
  schedule:
      - cron: '0 0 * * *'

jobs:
  check:
      name: Check for changes in file
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      
      - name: Run check
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run python app.py check --slack ${{secrets.SLACK_HOOK}} --slack ${{secrets.SLACK_HOOK_AT}}

      - name: Run tree
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run python app.py tree

      - name: Commit and push changes
        run: |
          git config --global user.name "wytamma"
          git config --global user.email "wytamma.wirth@me.com"
          if [ "$(git status --porcelain | head -1)" ]
          then
            git add -A
            git commit -m ":tada: Changes Found!"
            git push
          fi